name: farmicon1
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.5
  qr_mobile_vision: ^5.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  permission_handler: ^10.0.0
  path_provider: ^2.0.7
  pdf: ^3.6.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  http_parser: ^4.1.2
  qr_code_scanner_plus: ^2.0.10+1
  loading_animation_widget:

  # --------------------------- Network Connectivity Checker --------------------------------
  android_flutter_wifi: ^0.1.3
  connectivity_plus: ^6.1.2
  wifi_iot: ^0.3.19+1



#  flutter_launcher_icons: ^0.14.1
#  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
